
on:
  workflow_call:
    secrets:
      PROJECT_NAMESPACE:
        required: true
      NUGET_SOURCE:
        required: true
      NUGET_API_KEY:
        required: true
    inputs:
      version: 
        type: string
        required: false
        description: 'ci project version'
      timestamp: 
        type: string
        required: false
        description: 'ci project timestamp'
      artifact_path_cicd:
        type: string
        required: false
        description: 'ci project path to cicd files'
      artifact_path_bin: 
        type: string
        required: false
        description: 'ci project path to bin'

jobs:
  build-and-test:
    name: build and test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      name: checkout

    - name: setup .net
      uses: actions/setup-dotnet@v3

    - name: dotnet nuget add source github.com/albedoteam
      run: dotnet nuget add source $source -n github --username albedocodes --password $api_key --store-password-in-clear-text
      env:
        source: ${{ secrets.NUGET_SOURCE }}
        api_key: ${{ secrets.NUGET_API_KEY }}

    - run: dotnet restore
      name: dotnet restore

    - name: dotnet build
      run: dotnet build --configuration $configuration --no-restore
      env:
        configuration: ${{ github.ref_name == 'main' && 'Release' || 'Debug' }}
      
    - name: dotnet test
      run: dotnet test --verbosity normal
  
    - name: dotnet publish
      if: ${{ github.event_name == 'push' }}
      run: dotnet publish --configuration $configuration --no-restore -output build
      env:
        configuration: ${{ github.ref_name == 'main' && 'Release' || 'Debug' }}

    - name: publish cicd artifacts
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_path_cicd }}
        path: |
          src/_cicd
        
    - name: publish build artifacts
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_path_bin }}
        path: |
          build