
on:
  workflow_call:
    secrets:
      PROJECT_NAMESPACE:
        required: true
      NUGET_SOURCE:
        required: true
      NUGET_API_KEY:
        required: true
    inputs:
      version: 
        type: string
        required: true
        description: 'ci project version'
      timestamp: 
        type: string
        required: true
        description: 'ci project timestamp'
      artifact_path_cicd:
        type: string
        required: true
        description: 'ci project path to cicd files'
      artifact_path_bin: 
        type: string
        required: true
        description: 'ci project path to bin'
      artifact_path_nupkg: 
        type: string
        required: true
        description: 'ci project path to nupkg'
        
jobs:
  deploy-to-rc:
    name: deploy to rc
    needs: [ version-checker, build-and-test ]
    runs-on: ubuntu-latest
    environment:
      name: main
      url: https://a.b.com
    steps:

    - uses: actions/checkout@v3
      name: checkout

    - name: download cicd artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ needs.version-checker.outputs.artifact_path_cicd }}

    - name: download bin artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ needs.version-checker.outputs.artifact_path_bin }}

    - name: test
      run: echo 'ls -a'