name: Albedo Team CI SDK

on:
  push: 
    branches: [rc, main]
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-test-on-pr:
    name: build and test on pr
    if: ${{ github.event_name == 'pull_request' }}
    uses: albedoteam/.github/workflows/api-build-test-and-pack.yml@main
    secrets: inherit
  set-ci-configuration:
    name: set ci configuration
    if: ${{ github.event_name == 'push' }}
    uses: albedoteam/.github/workflows/set-ci-configuration@main
    secrets: inherit
  build-test-and-publish:
    name: build, test and publish
    needs: [set-ci-configuration]
    uses: albedoteam/.github/workflows/api-build-test-and-publish.yml@main
    with:
      version: ${{ needs.set-ci-configuration.outputs.version }}
      timestamp: ${{ needs.set-ci-configuration.outputs.timestamp }}
      artifact_path_cicd: ${{ needs.set-ci-configuration.outputs.artifact_path_cicd }}
      artifact_path_bin: ${{ needs.set-ci-configuration.outputs.artifact_path_bin }}
    secrets: inherit
  deploy:
    name: deploy
    needs: [build-test-and-publish]
    uses: albedoteam/.github/workflows/deploy.yml@main
    with:
      version: ${{ needs.set-ci-configuration.outputs.version }}
      timestamp: ${{ needs.set-ci-configuration.outputs.timestamp }}
      artifact_path_cicd: ${{ needs.set-ci-configuration.outputs.artifact_path_cicd }}
      artifact_path_bin: ${{ needs.set-ci-configuration.outputs.artifact_path_bin }}
    secrets: inherit
  create-release:
    name: create release
    if: ${{ github.ref_name == 'main' }}
    needs: [deploy]
    uses: albedoteam/.github/workflows/create-release.yml@main
    secrets: inherit